### ISSUE TITLE
CDMarkdownKit build failed on XCode 11.4

### ISSUE THREAD

**Issue by Aglezabad** [chrisdhaan/CDMarkdownKit#21]
## What did you do?
I've upgraded XCode from 11.3.1 to 11.4

## What did you expect to happen?
CDMarkdownKit built with successful results.

## What happened instead?
Build failed.
"Switch must be exhaustive on line 301 of CDMarkdownLabel.swift file."
<img width="1131" alt="Captura de pantalla 2020-03-25 a las 11 05 31" src="https://user-images.githubusercontent.com/1348276/77524963-8d182980-6e88-11ea-8037-d58f84f84d7d.png">

## CDMarkdownKit Environment

**CDMarkdownKit version:**  1.2.1
**Xcode version:**  11.4
**Swift version:**  5
**Platform(s) running CDMarkdownKit:**  iOS 13.3.1
**macOS version running Xcode:** Catalina 10.15.3 (19D76)

Best regards.

**Comment by kunass2** [comment]
Yes, I agree with the issue. Waiting for fix.

**Comment by arusa** [comment]
I get the same error. That's very strange... according to UITouch.Phase documentation there are no more states available, but maybe Swift still needs a "default" case because nevertheless those touch phase constants are just integers and not all integers are covered by the switch statement?

I have solved the problem temporarily by changing the last few lines to:

```
        case .stationary:
            break
        default:
            break
        }
```

**Comment by arusa** [comment]
OMG there are already better solutions available as pull request...

https://github.com/chrisdhaan/CDMarkdownKit/pull/23/commits/42d6ce2ac2f24f3e65532dc1944cc1b47a7ef85a

**Comment by chrisdhaan** [comment]
@Aglezabad @kunass2 @arusa a new release has been made with this fix. Closing issue.
